#!/bin/bash

# LTE Failover Setup Script for Ubuntu/Debian (Netplan/systemd-networkd)
# This script configures LTE alongside Ethernet, keeping Ethernet as primary
# to prevent SSH/Tailscale disconnections. Policy-Based Routing (PBR) handles the rest.

set -e

echo "----------------------------------------------------"
echo " Starting LTE Modem Setup (Safe Mode for SSH)"
echo "----------------------------------------------------"

# 1. Detect Interfaces
echo "[1/5] Detecting interfaces..."

# Find Primary Ethernet (Excluding loopback, tailscale, and USB/LTE enx...)
ETH_IF=$(ip -br link show | grep -E "^e(n|t)" | grep -v "enx" | awk '{print $1}' | head -n 1)
if [ -z "$ETH_IF" ]; then
    echo "Error: Could not detect primary Ethernet interface."
    exit 1
fi
ETH_MAC=$(cat /sys/class/net/$ETH_IF/address)
echo " -> Detected Ethernet: $ETH_IF ($ETH_MAC)"

# Find LTE Interface (Huawei Dongle usually shows as enx...)
# First try searching for enx interfaces
LTE_IF=$(ip -br link show | grep "enx" | awk '{print $1}' | head -n 1)

# If not found by enx, try to find by driver (cdc_ether)
if [ -z "$LTE_IF" ]; then
    LTE_IF=$(basename $(ls -l /sys/class/net/*/device/driver | grep cdc_ether | awk '{print $9}' | cut -d/ -f5 | head -n 1) 2>/dev/null || true)
fi

if [ -z "$LTE_IF" ]; then
    echo "Error: LTE Modem (Huawei) not detected. Please ensure it is plugged in."
    exit 1
fi
LTE_MAC=$(cat /sys/class/net/$LTE_IF/address)
echo " -> Detected LTE Interface: $LTE_IF ($LTE_MAC)"

# 2. Backup Existing Config
echo "[2/5] Backing up current netplan config..."
BACKUP_DIR="/etc/netplan/backup"
sudo mkdir -p $BACKUP_DIR
sudo cp /etc/netplan/*.yaml $BACKUP_DIR/ 2>/dev/null || true
echo " -> Backed up to $BACKUP_DIR"

# 3. Generate New Netplan Config
echo "[3/5] Generating new Netplan configuration..."
sudo tee /etc/netplan/00-installer-config.yaml <<EOF
# Generated by install_lte_single.sh
network:
  version: 2
  renderer: networkd
  ethernets:
    $ETH_IF:
      dhcp4: true
      dhcp6: true
      match:
        macaddress: $ETH_MAC
      set-name: $ETH_IF
      dhcp4-overrides:
        route-metric: 100
      dhcp6-overrides:
        route-metric: 100
    $LTE_IF:
      dhcp4: true
      dhcp6: true
      match:
        macaddress: $LTE_MAC
      set-name: $LTE_IF
      dhcp4-overrides:
        route-metric: 200
      dhcp6-overrides:
        route-metric: 200
EOF

# 4. Apply Configuration
echo "[4/5] Applying network configuration..."
sudo netplan apply
echo " -> Applied. Waiting 5 seconds for IP assignment..."
sleep 5

# 4.5 Register to PM2
echo "[4.5/5] Registering wifi-scheduler to PM2 (Stopped)..."
if [ -f "wifi_single/run_scheduler.sh" ]; then
    chmod +x wifi_single/run_scheduler.sh
    pm2 delete wifi-scheduler 2>/dev/null || true
    pm2 start wifi_single/run_scheduler.sh --name "wifi-scheduler" --no-autorestart
    pm2 stop wifi-scheduler
    pm2 save
else
    echo "[!] wifi_single/run_scheduler.sh not found. Skipping PM2 registration."
fi

# 5. Verification
echo "[5/5] Verifying setup..."
echo "--- Routing Table ---"
ip route | grep default || echo "No default route found!"

echo "--- LTE Connectivity Test ---"
if curl --interface $LTE_IF -s --connect-timeout 5 https://www.google.com > /dev/null; then
    echo " -> LTE Setup Successful: Connection verified via $LTE_IF"
else
    echo " -> LTE Setup Warning: Interface is up but cannot reach internet via $LTE_IF"
fi

echo "----------------------------------------------------"
echo " Done! Ethernet remains default (metric 100) to keep SSH alive."
echo " LTE is ready (metric 200) and will be managed via PBR."
echo "----------------------------------------------------"
