#!/bin/bash

# LTE Failover Setup Script for Ubuntu/Debian (Netplan/systemd-networkd)
# This script configures LTE alongside Ethernet, keeping Ethernet as primary
# to prevent SSH/Tailscale disconnections. Policy-Based Routing (PBR) handles the rest.

set -e

echo "----------------------------------------------------"
echo " Starting LTE Modem Setup (Safe Mode for SSH)"
echo "----------------------------------------------------"

# 1. Detect Primary Ethernet
echo "[1/4] Detecting primary interface..."
ETH_IF=$(ip -br link show | grep -E "^e(n|t)" | grep -v "enx" | awk '{print $1}' | head -n 1)
if [ -z "$ETH_IF" ]; then
    echo "Error: Could not detect primary Ethernet interface."
    exit 1
fi
ETH_MAC=$(cat /sys/class/net/$ETH_IF/address)
echo " -> Detected Ethernet: $ETH_IF ($ETH_MAC)"

# 2. Backup Existing Config
echo "[2/4] Backing up current netplan config..."
BACKUP_DIR="/etc/netplan/backup"
sudo mkdir -p $BACKUP_DIR
sudo cp /etc/netplan/*.yaml $BACKUP_DIR/ 2>/dev/null || true
echo " -> Backed up to $BACKUP_DIR"

# 3. Generate New Robust Netplan Config
echo "[3/4] Generating wildcard-based Netplan configuration..."
sudo tee /etc/netplan/00-installer-config.yaml <<EOF
# Generated by install_lte_single.sh (V3 - DNS Failover Robustness)
network:
  version: 2
  renderer: networkd
  ethernets:
    # 1. Primary Ethernet (Guaranteed Metric 100)
    $ETH_IF:
      dhcp4: true
      dhcp6: true
      match:
        macaddress: $ETH_MAC
      set-name: $ETH_IF
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
      dhcp4-overrides:
        route-metric: 100
        use-dns: false
      dhcp6-overrides:
        route-metric: 100
        use-dns: false
    
    # 2. Universal USB/LTE Modems (Guaranteed Metric 200 to prevent SSH hijack)
    lte-modems:
      match:
        name: "lte*"
      dhcp4: true
      dhcp6: true
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
      dhcp4-overrides:
        route-metric: 200
        use-dns: false
      dhcp6-overrides:
        route-metric: 200
        use-dns: false
        
    usb-modems:
      match:
        name: "enx*"
      dhcp4: true
      dhcp6: true
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
      dhcp4-overrides:
        route-metric: 200
        use-dns: false
      dhcp6-overrides:
        route-metric: 200
        use-dns: false
        
    usb-rndis:
      match:
        name: "usb*"
      dhcp4: true
      dhcp6: true
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
      dhcp4-overrides:
        route-metric: 200
        use-dns: false
      dhcp6-overrides:
        route-metric: 200
        use-dns: false
EOF

# 4. Apply Configuration
echo "[4/4] Applying network configuration..."
sudo netplan apply
echo " -> Applied. Waiting 5 seconds for IP assignment..."
sleep 5

# 5. Verification
echo "--- Routing Table ---"
ip route | grep default || echo "No default route found!"

echo "----------------------------------------------------"
echo " Done! Ethernet remains default (metric 100) to keep SSH alive."
echo " Any USB/LTE modem (enx*, lte*, usb*) will automatically get metric 200."
echo " DNS is globally forced to 8.8.8.8 to prevent resolving failures on fallback."
echo "----------------------------------------------------"

